/**
 * PDF Translation Loader
 *
 * Dynamically loads translations for PDF generation in any supported language.
 * This allows generating PDFs in different languages regardless of the current UI language.
 */

interface PDFTranslations {
  title: string
  date: string
  time: string
  items: string
  item: string
  qty: string
  unitPrice: string
  total: string
  grandTotal: string
  toman: string
  grams: string
  piece: string
  generatedBy: string
  tehranTime: string
}

/**
 * Loads translations for PDF generation in a specific language
 *
 * @param locale - Target locale (en, fa, ar)
 * @returns Promise with translations object
 */
export async function loadPDFTranslations(locale: string): Promise<PDFTranslations> {
  try {
    // Dynamically import the translation file for the target language
    const messages = await import(`../../../messages/${locale}.json`)

    return {
      title: messages.PDF?.title || 'Currency Exchange Calculator',
      date: messages.PDF?.date || 'Date',
      time: messages.PDF?.time || 'Time',
      items: messages.PDF?.items || 'Items',
      item: messages.PDF?.item || 'Item',
      qty: messages.PDF?.qty || 'Qty',
      unitPrice: messages.PDF?.unitPrice || 'Unit Price',
      total: messages.PDF?.total || 'Total',
      grandTotal: messages.PDF?.grandTotal || 'Grand Total',
      toman: messages.Calculator?.toman || 'Toman',
      grams: messages.Calculator?.grams || 'grams',
      piece: messages.Calculator?.piece || 'piece',
      generatedBy: messages.PDF?.generatedBy || 'Generated by Currency Exchange Calculator',
      tehranTime: messages.PDF?.tehranTime || 'Tehran Time',
    }
  } catch (error) {
    console.error(`Failed to load translations for locale "${locale}":`, error)

    // Fallback to English
    if (locale !== 'en') {
      console.warn('Falling back to English translations')
      return loadPDFTranslations('en')
    }

    // Ultimate fallback: hardcoded English
    return {
      title: 'Currency Exchange Calculator',
      date: 'Date',
      time: 'Time',
      items: 'Items',
      item: 'Item',
      qty: 'Qty',
      unitPrice: 'Unit Price',
      total: 'Total',
      grandTotal: 'Grand Total',
      toman: 'Toman',
      grams: 'grams',
      piece: 'piece',
      generatedBy: 'Generated by Currency Exchange Calculator',
      tehranTime: 'Tehran Time',
    }
  }
}
